### ISSUE TITLE
thêm âm thanh cho game

### ISSUE THREAD

**Issue by gnuh-naut** [Cong-Nghe-Phan-Mem-nhom-17/Gnoud-Gnoah#1]
thêm âm thanh để mô tả câu hỏi trong mỗi màn và âm thanh khi đáp án đúng

**Comment by Dang-Henry** [comment]
đã nhận công việc

**Comment by Gnoud-Gnoah** [comment]
Tôi xem phần audio này rồi nhưng mà hình như nó lỗi từ cái framework rồi. Kiểu này nhóm cần xem lại để fix phần lỗi đó.

**Comment by gnuh-naut** [comment]
thế khó nhỉ, mà liệu thêm audio bằng html có được không nhỉ

**Comment by Gnoud-Gnoah** [comment]
Huấn, ông học html rồi xem có thêm đc ko

**Comment by Dang-Henry** [comment]
về phần audio thì t vẫn chưa sửa được ở phaser.

**Comment by Dang-Henry** [comment]
nếu vẫn k được thì để t tìm cách thêm vào trong HTML sau nhé

**Comment by gnuh-naut** [comment]
Tôi thêm audio đc r

**Comment by Gnoud-Gnoah** [comment]
tôi thêm ảnh rồi nha ông thêm audio đi nha

**Comment by gnuh-naut** [comment]
tôi thêm âm thanh cho phần 1 màn 1 rồi, mọi người xem có ổn không, nếu không ổn thì báo tôi để tôi sửa luôn

**Comment by gnuh-naut** [comment]
tôi làm xong phần âm thanh cho game rồi đấy, mọi người vào xem được chưa

**Comment by Gnoud-Gnoah** [comment]
Phần âm thanh cả 3 phần ok rồi đó

**Comment by gnuh-naut** [comment]
Ok
