### ISSUE TITLE
thêm ảnh khi kết thúc mỗi màn

### ISSUE THREAD

**Issue by gnuh-naut** [Cong-Nghe-Phan-Mem-nhom-17/Gnoud-Gnoah#3]

**Comment by Dang-Henry** [comment]
đã nhận công việc nhé

**Comment by Gnoud-Gnoah** [comment]
Ok, i will create image over game with figma or get image on dragonlearn.

**Comment by gnuh-naut** [comment]
> Ok, i will create image over game with figma or get image on dragonlearn.

ok bro

**Comment by gnuh-naut** [comment]
Huấn lấy ảnh rồi đấy Dương thêm ảnh đi

**Comment by Dang-Henry** [comment]
xong rồi nhé bạn check giúp mk

**Comment by gnuh-naut** [comment]
ok

**Comment by gnuh-naut** [comment]
Tôi đã thêm ảnh xong rồi mọi người vào kiểm tra xem ổn chưa nha

**Comment by Dang-Henry** [comment]
ảnh đó kết thúc đẹp rồi đó

**Comment by gnuh-naut** [comment]
ok
