### ISSUE TITLE
Lấy ảnh kết thúc màn về rồi đẩy lên <ảnh dragonlearn>

### ISSUE THREAD

**Issue by gnuh-naut** [Cong-Nghe-Phan-Mem-nhom-17/Gnoud-Gnoah#4]

**Comment by Dang-Henry** [comment]
đã nhận công việc

**Comment by gnuh-naut** [comment]
> đã nhận công việc

Ok cố gắng làm nhanh nha

**Comment by Dang-Henry** [comment]
lấy ảnh màn kết thúc xong rồi đó. vào check cho t nhé 
![dragon](https://user-images.githubusercontent.com/61747767/79295985-5ae86d80-7f04-11ea-877c-864afb5bb243.png)

**Comment by gnuh-naut** [comment]
> lấy ảnh màn kết thúc xong rồi đó. vào check cho t nhé 
> ![dragon](https://user-images.githubusercontent.com/61747767/79295985-5ae86d80-7f04-11ea-877c-864afb5bb243.png)
> 

Ảnh ok rồi đấy push lên đi
