### ISSUE TITLE
Tạo icon audio 

### ISSUE THREAD

**Issue by gnuh-naut** [Cong-Nghe-Phan-Mem-nhom-17/Gnoud-Gnoah#5]

**Comment by Gnoud-Gnoah** [comment]
ok ông để tôi làm cái này cho

**Comment by gnuh-naut** [comment]
Ok làm xong thì báo tôi nha

**Comment by Gnoud-Gnoah** [comment]
Tôi vừa làm xong cho part 1 lesson 1 rồi

**Comment by gnuh-naut** [comment]
Ok để chiều tôi thêm audio

**Comment by gnuh-naut** [comment]
Ông thêm icon cả khi xuất hiện above vs below lúc chọn đúng nữa

**Comment by gnuh-naut** [comment]
Được rồi đấy, ông làm tiếp vs các phần còn lại đi. Để chiều tôi chuẩn bị audio, đến tối thì thêm vào

**Comment by Gnoud-Gnoah** [comment]
Ok tôi push thêm được image audio phần 2 lesson 1 rồi nha.

**Comment by gnuh-naut** [comment]
Ok mai tôi thêm audio vào

**Comment by gnuh-naut** [comment]
tôi thêm audio màn 1 xong r đấy, ông thêm icon vào màn 2 và 3 đi

**Comment by Gnoud-Gnoah** [comment]
Tôi làm xong thêm ảnh của màn 2 rồi nha ông thêm audio vào đi nha.

**Comment by gnuh-naut** [comment]
Ok giờ t thêm luôn

**Comment by Gnoud-Gnoah** [comment]
Tôi xem bài rồi, mọi thứ đều ổn chắc là chúng ta đóng issue này tại đây thôi!

**Comment by gnuh-naut** [comment]
Ok
