### ISSUE TITLE
Cải tiến mã nguồn và thêm các dấu chấm kết câu.

### ISSUE THREAD

**Issue by gnuh-naut** [Cong-Nghe-Phan-Mem-nhom-17/Gnoud-Gnoah#7]

**Comment by gnuh-naut** [comment]
đặt lại tên các biến nha. Nêu có ý tưởng cải tiến khác thì cmt lên đây để mọi người cùng thảo luận

**Comment by Dang-Henry** [comment]
refactor tất cả các biến và tên gọi lại luôn nhé

**Comment by Dang-Henry** [comment]
để tớ làm cho nhé

**Comment by gnuh-naut** [comment]
ok nếu có vấn đề gì thì viết lên đây nha

**Comment by Dang-Henry** [comment]
đã cải tiến mã nguồn.ae check xem nhé

**Comment by gnuh-naut** [comment]
Khá ổn rồi. Nếu có vấn đề thì tôi đưa lên đây
