### ISSUE TITLE
Thêm bộ đếm thời gian cho các màn chơi.

### ISSUE THREAD

**Issue by gnuh-naut** [Cong-Nghe-Phan-Mem-nhom-17/Gnoud-Gnoah#8]

**Comment by gnuh-naut** [comment]
mọi người cùng nghĩ cách thêm bộ đếm thời gian nha

**Comment by Dang-Henry** [comment]
thêm đếm thời gian cho từng câu hỏi để xem ai trả lời nhanh nhất rồi lưu lại kết quả nhỉ.

**Comment by gnuh-naut** [comment]
đúng rồi. mà t có ý tưởng rồi, để mai t làm thử, nếu thành công thì t sẽ gửi cho mọi người tham khảo

**Comment by Dang-Henry** [comment]
ok.có ý tưởng rồi thì cùng giải quyết thôi

**Comment by gnuh-naut** [comment]
ok

**Comment by Gnoud-Gnoah** [comment]
ok

**Comment by gnuh-naut** [comment]
mọi người xem thêm thế này đã ổn chưa? nếu chưa ổn thì cho t ý kiến để sửa.

**Comment by Dang-Henry** [comment]
thêm thời gian ổn rồi bạn ơi

**Comment by gnuh-naut** [comment]
Ok
